# Generated by Django 4.0.6 on 2023-05-12 22:05

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=app_users.models.avatar_path),
        ),
    ]
