# Generated by Django 4.1.3 on 2022-12-24 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Загаловок')),
                ('options', models.TextField(max_length=1000, verbose_name='Описание')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('flag', models.CharField(choices=[('Active', 'Активно'), ('Deactive', 'Неактивно')], max_length=20)),
            ],
            options={
                'db_table': 'News',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='Имя пользователя')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_news', to='app_news.news')),
            ],
            options={
                'db_table': 'Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
